= Getting started

Angela provides a Java API to handle a Terracotta cluster lifecycle.
It also provides a set of utility methods to help with testing (e.g. network controlling for HA testing)

It can set up a TSA from :

 - a Kit tarball
 - a local build

It can install the cluster locally or remotely

It can execute functions that contain client code locally or remotely

== Initial setup

For running tests on a node angela expects a directory at `/data/angela` to store all its metadata.
So make sure that this directory exists or can be created before running any tests.
For more details on what what that directory is used for, refer to <<directory-structure.adoc#, Angela Directory Structure>>

== Tsa Cluster example

Given the following cluster configuration:

[source,xml]
----
include::../resources/tc-config-a.xml[tags=servers]
----

We expect the TSA to contain one Terracotta server running on localhost, and this will be automatically resolved by Angela.
We can ask now Angela to setup such a cluster:

[source,java]
----
include::../java/GettingStarted.java[tags=configureCluster]
----
<1> Create a custom configuration context that is going to hold all the configurable bits
<2> Define the TSA config
<3> Specify the Terracotta cluster topology
<4> Specify the Terracotta distribution : version, package type (KIT)
<5> Specify the Terracotta cluster config
<6> Create a Tsa logical instance that serves as an endpoint to call functionalities regarding the Tsa lifecycle
<7> Install the Tsa from the distribution on the appropriate server(s) (localhost in this case)
<8> Start all servers from the Tsa
<9> Stop all Terracotta servers and cleans up the installation

== Tsa API

[source,java]
----
include::../java/GettingStarted.java[tags=showTsaApi]
----
<1> Install all Terracotta servers for the given topology
<2> Start all Terracotta servers
<3> Get the reference of the active server. Null is returned if there is none. An exception is throw if there are more than one
<4> Get the references of all active servers. Get an empty collection if there are none.
<5> Get the reference of the passive server. Null is returned if there is none. An exception is throw if there are more than one
<6> Get the references of all passive servers. Get an empty collection if there are none.
<7> Stop all Terracotta servers
<8> Start one Terracotta server
<9> Stop one Terracotta server
<10> Get the current state of the Terracotta server

== Dynamic config support
Angela 3 adds support for dynamic config feature of Terracotta.

The dynamic config feature adds the possibility to change the cluster topology dynamically while the cluster is up.

=== Dynamic config Concepts

Therefore, a number of new concepts have been introduced:

- There is no tc-config.xml file anymore. A cluster is defined in a *repository* (which is a folder on the disk containing the cluster definition)

- a Terracotta server is named a *node*

- the _config-tool_ allows to *attach* (add) and *detach* (remove) nodes from the cluster

- the _config-tool_ allows to *activate* (define) new stripes in the cluster.

=== Dynamic config API

To tackle with this new functionality, Angela provides a specific API for the dynamic config:

Instead of giving the reference of the tc-config file :

```
TcConfig.tcConfig(version(TERRACOTTA_VERSION), "/some/tc-config.xml")
```

We define the cluster topology and settings using the DynamicConfigManager.dynamicCluster() method

```
DynamicConfigManager.dynamicCluster()
                stripe(
                    server("server-1", "localhost")
                        .tsaPort(9410)
                        .tsaGroupPort(9411)
                        .configRepo("terracotta1/repository")
                        .logs("terracotta1/logs")
                        .metaData("terracotta1/metadata")
                        .failoverPriority("availability")
                    )
                )
```

A cluster can be started with the usual start/startAll methods

```
Tsa.startAll()
```

However, nodes are not ready yet, they are started in a new *DIAGNOSTIC* mode, which means that they are waiting for the user to attach them to the cluster, and to be activated (to be effective)

Therefore, after starting the nodes, you need to attach them

```
configTool.attachAll()
```

And finally:

```
configTool.activate()
```
this does several things:

- Set a cluster name

- Install and validate the license

- Validate the configuration for each node

- Creating (saving) the validated cluster config into the config repository

- Restart the nodes


Those three operations can be chained:

```
Tsa.startAll();
configTool.attachAll();
configTool.activate()
```

When the cluster is up, you can dynamically attach or detach new nodes.

```
   configTool.attachNode(0, server("server-3", "localhost")
          .tsaPort(9610)
          .tsaGroupPort(9611)
          .configRepo("terracotta3/repository")
          .logs("terracotta3/logs")
          .metaData("terracotta3/metadata")
          .failoverPriority("availability"));
```

```
      // detach the 2nd node (index=1) from the 1st stripe (index=0)
      TerracottaServer toDetach = tsa.getServer(0, 1); // 1st stripe, 2nd node
      configTool.detachNode(0, 1);
      tsa.stop(toDetach);
```


[source,java]
----
include::../java/GettingStarted.java[tags=showDynamicTsaApi]
----
<1> Define an initial dynamic cluster topology
<2> Start all Terracotta servers
<3> Attach all servers defined in the initial topology to create an unconfigured cluster
<4> Attach a single server stripe dynamically to the cluster
<5> Detach the second node from the first stripe
<6> Stop the detached server
<7> Activate the cluster


== Client array example

[source,java]
----
include::../java/GettingStarted.java[tags=runClient]
----
<1> Define the client array config
<2> Define the client array topology
<3> Specify the distribution from which to install the client jars
<4> Specify the list of hosts that are going to be used by this client array (two clients, both on localhost in this case)
<5> Create a client array on the remote servers
<6> Execute the lambda on all the remote clients
<7> Wait until all the clients finish their execution

== Full example

See class EhcacheTest

[source,java]
----
include::../../../../integration-test/src/test/java/org/terracotta/angela/EhcacheTest.java[]
----




